# Generated by Django 5.1 on 2024-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('can_view', 'Can view MyModel'), ('can_create', 'Can create MyModel'), ('can_edit', 'Can edit MyModel'), ('can_delete', 'Can delete MyModel')],
            },
        ),
    ]
